### ISSUE TITLE
Usage of innerHTML

### ISSUE THREAD

**Issue by stewartrule** [hyperapp/render#8] opened 2018-04-29 14:00 UTC
Hi, I'm working on a simple component to insert (markdown generated) html into an element using the `oncreate` and `onupdate` lifecycle hooks. Everything seemed ok until I viewed the source of the page and noticed the innerHTML wasn't being rendered on the server since `oncreate` only triggers after the element has been created.

Since we kind of need it for SEO, I tried a couple of things and found out that adding an `innerHTML` attribute/prop does render it on the server, although that doesn't work client-side.

I am not sure if this is intentional or a bug, since I couldn't find it anywhere in the documentation. Is this the way go or can we expect it to be gone in a next release?

```tsx
const setHtml = (html: string) => (el: HTMLElement) => el.innerHTML = html;

const UnsafeHtml = ({ html, tag = 'div' }: Props) =>
  h(tag, {
    innerHTML: html, // ssr only?
    oncreate: setHtml(html),
    onupdate: setHtml(html),
  });
```

**Comment by frenzzy** [comment] 2018-05-02 07:37
`innerHTML` attribute works fine [isomorphically](http://nerds.airbnb.com/isomorphic-javascript-future-web-apps/) (on both client-side and server-side):

```js
const html = '<h1>HTML</h1>'
const view = () => <div innerHTML={html} />
```

You do not need to additionally use lifecycle events.

- `hyperapp` demo: https://codepen.io/frenzzy/pen/MGmObE/left/?editors=0010
- `@hyperapp/render` demo: https://codepen.io/frenzzy/pen/YLVEVo/left/?editors=0010

**Comment by frenzzy** [comment] 2018-05-02 09:01
@stewartrule looks like you found a bug.

[Hydration (recycling/mounting)](https://github.com/hyperapp/hyperapp#mounting) feature in hyperapp works wrong when you are using `innerHTML`.
Reproducible demo: https://codepen.io/frenzzy/pen/NMjydV/left/?editors=0010
Using [node `key`](https://github.com/hyperapp/hyperapp#keys) does not help with this issue.

cc @jorgebucaran

**Comment by frenzzy** [comment] 2018-05-02 13:18
I think you can use a `RawHTML` component as a temporary workaround:
```js
<RawHTML>{html}</RawHTML>
```
```js
const RawHTML = ({ tagName: Node = 'div', ...props }, children) => (
  <Node
    {...props}
    innerHTML={children}

    // do not forget to remove oncreate attribute
    // when innerHTML hydration in hyperapp will be fixed
    oncreate={element => {
      element.innerHTML = children
      if (props.oncreate) props.oncreate(element)
    }} 
  />
)
```
Demo: https://codepen.io/frenzzy/pen/deWKwj?editors=0010

**Comment by stewartrule** [comment] 2018-05-02 17:38
Looks good to me for the moment. Thanks for taking a look :)

**Comment by frenzzy** [comment] 2018-05-07 07:17
Closing in favor of https://github.com/hyperapp/hyperapp/pull/688

**Closed by frenzzy** 2018-05-07 07:17 UTC
